apiVersion: v1
kind: Service
metadata:  
  name: titan-ccp-history
spec:
  type: NodePort
  selector:    
    app: titan-ccp-history
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31102
    protocol: TCP